// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIJNVm_tBy0Xa6OU9h_Y5NDwwxUpG2UrU',
    appId: '1:900810841507:web:a7eef8d096731f35534e16',
    messagingSenderId: '900810841507',
    projectId: 'majdurdemo',
    authDomain: 'majdurdemo.firebaseapp.com',
    storageBucket: 'majdurdemo.firebasestorage.app',
    measurementId: 'G-D1C221VBHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO06UpLf67k9nHXReUCbT_lDs-3OQz42s',
    appId: '1:900810841507:android:4075b0e124ef632e534e16',
    messagingSenderId: '900810841507',
    projectId: 'majdurdemo',
    storageBucket: 'majdurdemo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcv_va5EoyAk6SusH56JpGJ9lVXKWpBgg',
    appId: '1:900810841507:ios:693887a605a5c2ca534e16',
    messagingSenderId: '900810841507',
    projectId: 'majdurdemo',
    storageBucket: 'majdurdemo.firebasestorage.app',
    androidClientId: '900810841507-81fugpu382k33neqskthbjm3b5aecekf.apps.googleusercontent.com',
    iosClientId: '900810841507-2ptn0lcq80nm1197k4jjtan691kacp3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.majduradda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcv_va5EoyAk6SusH56JpGJ9lVXKWpBgg',
    appId: '1:900810841507:ios:693887a605a5c2ca534e16',
    messagingSenderId: '900810841507',
    projectId: 'majdurdemo',
    storageBucket: 'majdurdemo.firebasestorage.app',
    androidClientId: '900810841507-81fugpu382k33neqskthbjm3b5aecekf.apps.googleusercontent.com',
    iosClientId: '900810841507-2ptn0lcq80nm1197k4jjtan691kacp3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.majduradda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIJNVm_tBy0Xa6OU9h_Y5NDwwxUpG2UrU',
    appId: '1:900810841507:web:f5c6431b7b7cbac9534e16',
    messagingSenderId: '900810841507',
    projectId: 'majdurdemo',
    authDomain: 'majdurdemo.firebaseapp.com',
    storageBucket: 'majdurdemo.firebasestorage.app',
    measurementId: 'G-2MZPWYE3BG',
  );

}